import './globals.css'
import { Aboreto, Arapey, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const aboreto = Aboreto({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-aboreto'
})

const arapey = Arapey({ 
  weight: '400',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arapey'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${aboreto.variable} ${arapey.variable} ${inter.className}`}>{children}</body>
    </html>
  )
}
